Repository 6-six-Days/Six_Days_CodingTube, pull requests merged in 2023-09, with the labels that each got.

#3 [DESIGN] : 🎨 Detailpage
  app/src/main/res/drawable/happydog2.png
  app/src/main/res/drawable/ic_cotube_text.png
  app/src/main/res/drawable/ic_shared.png
  app/src/main/res/drawable/ic_star.png
  app/src/main/res/drawable/round_button.xml
  app/src/main/res/layout/fragment_detail_page.xml
  app/src/main/res/values/colors.xml
Labels: UI

#6 [FEAT] : ⚙️ 메인화면 ui/프레그먼트 레사이클러 뷰 , 어댑터 추가, 확인용 더미데이터 추가
  .idea/deploymentTargetDropDown.xml
  app/.idea/.gitignore
  app/.idea/gradle.xml
  app/.idea/misc.xml
  app/.idea/vcs.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bluecodingtube/Best_Recycler_View.kt
  app/src/main/java/com/example/bluecodingtube/Category_Recycler_View.kt
  app/src/main/java/com/example/bluecodingtube/HomePage.kt
  app/src/main/java/com/example/bluecodingtube/MainActivity.kt
  app/src/main/java/com/example/bluecodingtube/Word_Category_Recycler_View.kt
  app/src/main/java/com/example/bluecodingtube/adapter/BestRecyclerViewAdapter.kt
  app/src/main/java/com/example/bluecodingtube/adapter/CategoryRecyclerViewAdapter.kt
  app/src/main/java/com/example/bluecodingtube/adapter/WordCategoryRecyclerViewAdapter.kt
  app/src/main/java/com/example/bluecodingtube/dataclass/Item.kt
  app/src/main/res/drawable/arrow.png
  app/src/main/res/drawable/star.png
  app/src/main/res/layout/activity_best_recycler_view.xml
  app/src/main/res/layout/activity_category_recycler_view.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_word_category_recycler_view.xml
  app/src/main/res/layout/fragment_home_page.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#8 🆕 Feat/splash
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bluecodingtube/Splash.kt
  app/src/main/res/anim/none.xml
  app/src/main/res/anim/slide_down_enter.xml
  app/src/main/res/anim/slide_down_exit.xml
  app/src/main/res/anim/slide_left_enter.xml
  app/src/main/res/anim/slide_left_exit.xml
  app/src/main/res/anim/slide_right_enter.xml
  app/src/main/res/anim/slide_right_exit.xml
  app/src/main/res/drawable/splash.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_detail_page.xml
Labels: UI

#9 Feature/search page
  app/src/main/java/com/example/bluecodingtube/SearchPage.kt
  app/src/main/java/com/example/bluecodingtube/adapter/SearchPageAdapter.kt
  app/src/main/java/com/example/bluecodingtube/adapter/searchData.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search_page.xml
Labels: feature

#10 [FEAT] : ⚙️ Feature/retrofit 레트로핏 API 요청
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bluecodingtube/data/YouTubeData.kt
  app/src/main/java/com/example/bluecodingtube/service/AuthorizationInterceptor.kt
  app/src/main/java/com/example/bluecodingtube/service/RetrofitClient.kt
  app/src/main/java/com/example/bluecodingtube/service/YouTubeService.kt
  app/src/main/java/com/example/bluecodingtube/service/api/SixDays.kt
  app/src/main/java/com/example/bluecodingtube/viewModel/getYoutubeVideo.kt
  app/src/main/res/values/string_api_key.xml
Labels: feature

#11 [LITTLE_FIX] : 🔧 : splash 를 true로 변경 (mainactivity와 연결함)
  app/src/main/AndroidManifest.xml
Labels: feature

#12 [DESIGN] : 🎨 My Page UI 작성
  app/build.gradle.kts
  app/src/main/res/drawable/codeimage.png
  app/src/main/res/layout/fragment_my_page.xml
Labels: UI
