Repository 6-six-Days/Six_Days_CodingTube, pull requests merged in 2023-10, with the labels that each got.

#14 [FEAT] : ⚙️ Search page 선택시 Detail page로 변경 및 Detailpage [ Fragment >…
  .idea/vcs.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bluecodingtube/DetailPage.kt
  app/src/main/java/com/example/bluecodingtube/DetailpageActivity.kt
  app/src/main/java/com/example/bluecodingtube/MyPage.kt
  app/src/main/java/com/example/bluecodingtube/adapter/SearchPageAdapter.kt
  app/src/main/java/com/example/bluecodingtube/adapter/searchData.kt
  app/src/main/res/layout/activity_detailpage.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: bug, feature

#15 Feat/detailpage
  app/src/main/java/com/example/bluecodingtube/adapter/SearchPageAdapter.kt
Labels: bug

#19 Fix / DataClass 수정
  app/src/main/java/com/example/bluecodingtube/DetailpageActivity.kt
  app/src/main/java/com/example/bluecodingtube/SearchPage.kt
  app/src/main/java/com/example/bluecodingtube/adapter/SearchPageAdapter.kt
  app/src/main/java/com/example/bluecodingtube/adapter/searchData.kt
  app/src/main/java/com/example/bluecodingtube/data/YouTubeData.kt
  app/src/main/java/com/example/bluecodingtube/dataclass/searchData.kt
Labels: Fix

#20 [Feat] : Glide.부분추가
  app/src/main/java/com/example/bluecodingtube/DetailpageActivity.kt
  app/src/main/java/com/example/bluecodingtube/dataclass/searchData.kt
  app/src/main/res/layout/activity_detailpage.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home_page.xml
Labels: feature

#21 [FEAT] : ⚙️: mypage로 화면 전환2
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/bluecodingtube/DetailpageActivity.kt
  app/src/main/res/layout/activity_detailpage.xml
Labels: feature

#23 Feature/search page keyword
  app/src/main/java/com/example/bluecodingtube/MainActivity.kt
  app/src/main/java/com/example/bluecodingtube/SearchPage.kt
  app/src/main/java/com/example/bluecodingtube/adapter/SearchPageAdapter.kt
  app/src/main/java/com/example/bluecodingtube/adapter/ViewPagerAdapter.kt
  app/src/main/java/com/example/bluecodingtube/service/YoutubeApiService.kt
  app/src/main/res/layout/fragment_search_page.xml
  app/src/main/res/values/themes.xml
Labels: feature, Fix

#24 [DESIGN] : 🎨 Detailpage 레이아웃 디자인 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/bluecodingtube/DetailpageActivity.kt
  app/src/main/res/layout/activity_detailpage.xml
  app/src/main/res/layout/activity_main.xml
Labels: UI

#27 [FEAT] : ⚙️ 좋아요 기능
  app/src/main/java/com/example/bluecodingtube/DetailpageActivity.kt
  app/src/main/java/com/example/bluecodingtube/MainActivity.kt
  app/src/main/java/com/example/bluecodingtube/MyPage.kt
  app/src/main/java/com/example/bluecodingtube/MyPageFragment.kt
  app/src/main/java/com/example/bluecodingtube/adapter/LikedItemsAdapter.kt
  app/src/main/java/com/example/bluecodingtube/util/Util.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/like_item.xml
Labels: feature
